export const CATEGORIES = [
  { id: 1, name: "Perfumes", slug: "perfumes", description: "Signature scents and luxury fragrances.", productCount: 6 },
  { id: 2, name: "Daily Use", slug: "daily-use", description: "Premium essentials for everyday life.", productCount: 6 },
  { id: 3, name: "Skincare", slug: "skincare", description: "Rejuvenating and nourishing routines.", productCount: 6 },
  { id: 4, name: "Electronics", slug: "electronics", description: "State-of-the-art modern devices.", productCount: 6 },
  { id: 5, name: "Clothing", slug: "clothing", description: "Haute couture and ready-to-wear fashion.", productCount: 6 },
  { id: 6, name: "Home Decor", slug: "home-decor", description: "Elegant accents for your living space.", productCount: 6 },
  { id: 7, name: "Accessories", slug: "accessories", description: "The perfect finishing touches.", productCount: 6 },
];

export const PRODUCTS = [
  // PERFUMES
  { id: 101, name: "Oud Noir Extrait", description: "A mysterious and deeply luxurious fragrance blending rare oud wood with dark amber and hints of spice. Long-lasting and exceptionally memorable.", price: 285.00, categoryId: 1, categoryName: "Perfumes", rating: 3.7, reviewCount: 3, inStock: true, featured: true, badge: "Bestseller", imageUrl: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80" },
  { id: 102, name: "Rose d'Or Eau de Parfum", description: "An opulent bouquet of Bulgarian rose, saffron, and white musk. Timeless femininity bottled in liquid gold.", price: 195.00, originalPrice: 240.00, categoryId: 1, categoryName: "Perfumes", rating: 4.0, reviewCount: 3, inStock: true, featured: false, badge: "Sale", imageUrl: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=800&q=80" },
  { id: 103, name: "Amber Soleil", description: "Warm amber and vanilla accord layered with bergamot and cedarwood. A scent that wraps you in pure comfort.", price: 165.00, categoryId: 1, categoryName: "Perfumes", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=800&q=80" },
  { id: 104, name: "Noir Vetiver", description: "Deep, smoky vetiver balanced by iris and black pepper. For those who command a room the moment they enter.", price: 230.00, categoryId: 1, categoryName: "Perfumes", rating: 4.0, reviewCount: 3, inStock: true, featured: false, badge: "New Arrival", imageUrl: "https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=800&q=80" },
  { id: 105, name: "Neroli Blanche", description: "Crisp Italian neroli, jasmine petals, and a hint of white tea. The freshest expression of Mediterranean luxury.", price: 145.00, categoryId: 1, categoryName: "Perfumes", rating: 4.0, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&q=80" },
  { id: 106, name: "Midnight Oud Royale", description: "An ultra-premium oud accord blended with Turkish rose and sandalwood. A masterpiece for the true connoisseur.", price: 420.00, categoryId: 1, categoryName: "Perfumes", rating: 4.0, reviewCount: 3, inStock: true, featured: false, badge: "Limited Edition", imageUrl: "https://images.unsplash.com/photo-1594035910387-fea47714263f?w=800&q=80" },

  // DAILY USE
  { id: 201, name: "Charcoal Purifying Wash", description: "Daily gentle cleanser infused with activated charcoal to draw out impurities without stripping moisture.", price: 45.00, categoryId: 2, categoryName: "Daily Use", rating: 4.0, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&q=80" },
  { id: 202, name: "Eucalyptus Mint Shampoo", description: "A salon-grade shampoo that cleanses deeply and leaves hair glossy, fragrant, and visibly thicker.", price: 38.00, categoryId: 2, categoryName: "Daily Use", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80" },
  { id: 203, name: "Argan Oil Conditioner", description: "Pure Moroccan argan oil blended with silk proteins. Transforms dry, frizzy hair into silken perfection.", price: 42.00, categoryId: 2, categoryName: "Daily Use", rating: 4.0, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80" },
  { id: 204, name: "Luxe Body Lotion", description: "24-hour moisturising lotion enriched with shea butter and vitamin E for softer, luminous skin all day.", price: 55.00, categoryId: 2, categoryName: "Daily Use", rating: 3.7, reviewCount: 3, inStock: true, featured: false, badge: "Bestseller", imageUrl: "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=800&q=80" },
  { id: 205, name: "Charcoal Whitening Toothpaste", description: "Activated charcoal and coconut oil formula for a naturally white, sparkling smile every morning.", price: 22.00, categoryId: 2, categoryName: "Daily Use", rating: 4.0, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1622928286296-39fe5b00c1d6?w=800&q=80" },
  { id: 206, name: "Bamboo Fibre Bath Towel Set", description: "Ultra-plush towel set woven from organic bamboo fibre. Hypoallergenic, quick-drying, and irresistibly soft.", price: 78.00, categoryId: 2, categoryName: "Daily Use", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1545173168-9f1947eebb7f?w=800&q=80" },

  // SKINCARE
  { id: 301, name: "Radiance Vitamin C Serum", description: "An ultra-concentrated serum that brightens, firms, and smooths skin tone while delivering deep hydration.", price: 120.00, originalPrice: 150.00, categoryId: 3, categoryName: "Skincare", rating: 3.7, reviewCount: 3, inStock: true, featured: true, imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80" },
  { id: 302, name: "Retinol Night Cream", description: "Clinical-strength 0.5% retinol combined with hyaluronic acid. Wake up to visibly smoother, younger-looking skin.", price: 145.00, categoryId: 3, categoryName: "Skincare", rating: 4.0, reviewCount: 3, inStock: true, featured: false, badge: "Bestseller", imageUrl: "https://images.unsplash.com/photo-1617897903246-719242758050?w=800&q=80" },
  { id: 303, name: "Hyaluronic Acid Moisturiser", description: "Lightweight yet intensely hydrating formula with triple-weight hyaluronic acid for all skin types.", price: 85.00, categoryId: 3, categoryName: "Skincare", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800&q=80" },
  { id: 304, name: "24K Gold Eye Mask", description: "Real 24-karat gold-infused patches that de-puff, hydrate, and illuminate the delicate under-eye area.", price: 68.00, categoryId: 3, categoryName: "Skincare", rating: 4.0, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&q=80" },
  { id: 305, name: "SPF 50 Tinted Sunscreen", description: "Invisible broad-spectrum sun protection with a subtle tint for a natural, healthy glow. PA++++.", price: 52.00, categoryId: 3, categoryName: "Skincare", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1556228841-a3c527ebefe5?w=800&q=80" },
  { id: 306, name: "Rose Quartz Facial Roller", description: "Authentic rose quartz roller that boosts circulation, reduces puffiness, and enhances product absorption.", price: 95.00, categoryId: 3, categoryName: "Skincare", rating: 4.0, reviewCount: 3, inStock: true, featured: false, badge: "New Arrival", imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80" },

  // ELECTRONICS
  { id: 401, name: "Aura Noise-Cancelling Headphones", description: "Immersive high-fidelity audio wrapped in premium brushed aluminum and plush leather earcups.", price: 499.00, categoryId: 4, categoryName: "Electronics", rating: 3.7, reviewCount: 3, inStock: true, featured: true, imageUrl: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80" },
  { id: 402, name: "Pro Smartwatch Ultra", description: "Titanium case with sapphire crystal display. Health tracking, GPS, and 10-day battery life.", price: 849.00, categoryId: 4, categoryName: "Electronics", rating: 4.0, reviewCount: 3, inStock: true, featured: false, badge: "New Arrival", imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80" },
  { id: 403, name: "Portable Lossless DAC Amp", description: "Studio-grade digital-to-analog converter for audiophiles on the go. Supports MQA and Hi-Res audio.", price: 320.00, categoryId: 4, categoryName: "Electronics", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80" },
  { id: 404, name: "4K Ultra-Slim Monitor", description: "27-inch 4K IPS panel with 144Hz refresh rate, zero-bezel design, and factory colour calibration.", price: 1199.00, categoryId: 4, categoryName: "Electronics", rating: 4.0, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80" },
  { id: 405, name: "Wireless Mechanical Keyboard", description: "Premium CNC-aluminium body, tactile switches, and Bluetooth 5.2. The pinnacle of desktop luxury.", price: 275.00, categoryId: 4, categoryName: "Electronics", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80" },
  { id: 406, name: "True Wireless Earbuds Pro", description: "ANC earbuds with 40dB noise cancellation, LDAC support, and 36-hour total battery life.", price: 349.00, originalPrice: 399.00, categoryId: 4, categoryName: "Electronics", rating: 4.0, reviewCount: 3, inStock: true, featured: false, badge: "Sale", imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80" },

  // CLOTHING
  { id: 501, name: "Midnight Silk Robe", description: "Handcrafted from 100% pure mulberry silk. Drapes flawlessly for unparalleled nighttime luxury.", price: 350.00, categoryId: 5, categoryName: "Clothing", rating: 3.7, reviewCount: 3, inStock: true, featured: true, badge: "New Arrival", imageUrl: "https://images.unsplash.com/photo-1510173489-a4b2a35e6b01?w=800&q=80" },
  { id: 502, name: "Merino Wool Overcoat", description: "Tailored from grade-A merino wool. A classic silhouette that transitions effortlessly from boardroom to evening.", price: 720.00, categoryId: 5, categoryName: "Clothing", rating: 4.0, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=800&q=80" },
  { id: 503, name: "Cashmere Turtleneck", description: "Superfine Grade-A cashmere in a relaxed-fit turtleneck. Impossibly light, impossibly warm.", price: 290.00, categoryId: 5, categoryName: "Clothing", rating: 3.7, reviewCount: 3, inStock: true, featured: false, badge: "Bestseller", imageUrl: "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=800&q=80" },
  { id: 504, name: "Silk Dress Shirt", description: "100% charmeuse silk dress shirt with mother-of-pearl buttons. Unmatched drape and lustre.", price: 185.00, categoryId: 5, categoryName: "Clothing", rating: 4.0, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80" },
  { id: 505, name: "Linen Tailored Blazer", description: "Relaxed Italian linen blazer with structured shoulders. The summer wardrobe essential for elevated casual.", price: 420.00, categoryId: 5, categoryName: "Clothing", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80" },
  { id: 506, name: "High-Rise Leather Trousers", description: "Buttery-soft lambskin leather trousers with a sleek high-rise silhouette and side-zip closure.", price: 540.00, categoryId: 5, categoryName: "Clothing", rating: 4.0, reviewCount: 3, inStock: true, featured: false, badge: "New Arrival", imageUrl: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80" },

  // HOME DECOR
  { id: 601, name: "Golden Hour Table Lamp", description: "Minimalist brass geometry meets warm diffused light. A striking addition to any modern study or bedside.", price: 245.00, categoryId: 6, categoryName: "Home Decor", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80" },
  { id: 602, name: "Cashmere Throw Blanket", description: "Woven from the finest sustainably sourced Mongolian cashmere. Incredibly soft and incredibly warm.", price: 420.00, categoryId: 6, categoryName: "Home Decor", rating: 4.0, reviewCount: 3, inStock: true, featured: true, badge: "Limited Edition", imageUrl: "https://images.unsplash.com/photo-1580893246395-52aead8960dc?w=800&q=80" },
  { id: 603, name: "Marble Side Table", description: "Hand-cut Carrara marble top on a matte black powder-coated steel frame. Functional art for your living room.", price: 680.00, categoryId: 6, categoryName: "Home Decor", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80" },
  { id: 604, name: "Scented Candle Trio", description: "Three hand-poured soy candles — Cedarwood, Bergamot & Amber — in hand-blown glass vessels.", price: 95.00, categoryId: 6, categoryName: "Home Decor", rating: 4.0, reviewCount: 3, inStock: true, featured: false, badge: "Bestseller", imageUrl: "https://images.unsplash.com/photo-1602928321679-560bb453f190?w=800&q=80" },
  { id: 605, name: "Geometric Brass Vase", description: "Handcrafted solid-brass vase with angular geometric facets. A bold centrepiece for contemporary interiors.", price: 175.00, categoryId: 6, categoryName: "Home Decor", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800&q=80" },
  { id: 606, name: "Linen Curtain Set", description: "Floor-to-ceiling linen curtains in natural ecru. Light-filtering weave for warmth without darkness.", price: 310.00, categoryId: 6, categoryName: "Home Decor", rating: 4.0, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80" },

  // ACCESSORIES
  { id: 701, name: "Artisan Leather Tote", description: "A timeless silhouette crafted from full-grain Italian leather with solid brass hardware.", price: 680.00, categoryId: 7, categoryName: "Accessories", rating: 3.7, reviewCount: 3, inStock: true, featured: true, imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80" },
  { id: 702, name: "Silk Square Scarf", description: "100% Italian silk scarf with hand-rolled edges and a hand-painted botanical motif. Limited run.", price: 220.00, categoryId: 7, categoryName: "Accessories", rating: 4.0, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&q=80" },
  { id: 703, name: "Aviator Sunglasses", description: "Titanium frame with polarised gold-mirror lenses. UV400 protection wrapped in iconic style.", price: 295.00, categoryId: 7, categoryName: "Accessories", rating: 3.7, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80" },
  { id: 704, name: "Crocodile-Print Belt", description: "Hand-dyed, embossed calfskin belt with a solid gold-plated double-pin buckle. Unmatched craftsmanship.", price: 180.00, categoryId: 7, categoryName: "Accessories", rating: 4.0, reviewCount: 3, inStock: true, featured: false, imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80" },
  { id: 705, name: "Leather Billfold Wallet", description: "Slim 8-card wallet in hand-stitched full-grain leather. Ages beautifully, lasts a lifetime.", price: 145.00, categoryId: 7, categoryName: "Accessories", rating: 3.7, reviewCount: 3, inStock: true, featured: false, badge: "Bestseller", imageUrl: "https://images.unsplash.com/photo-1517254456976-1dd97f7a9117?w=800&q=80" },
  { id: 706, name: "Statement Pearl Necklace", description: "Freshwater baroque pearls on a 14K gold chain. Where classic elegance meets contemporary edge.", price: 395.00, categoryId: 7, categoryName: "Accessories", rating: 4.0, reviewCount: 3, inStock: true, featured: false, badge: "New Arrival", imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80" },
];
